import Head from "next/head";
import Card from "./components/Card";
import { useEffect, useState } from "react";

import styles from "../styles/Home.module.css";

export default function Home() {
  const [dogs, setDogs] = useState([]);

  useEffect(() => {
    const fetchDogs = async () => {
      const data = await fetch("/api/fetchDogs").then((data) => data.json());

      setDogs(data);
    };

    fetchDogs();
  }, []);

  return (
    <>
      <Head>
        <title>Dog API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/jgthms/minireset.css@master/minireset.min.css"
        />
      </Head>
      <main className={styles.main}>
        {dogs?.map(({ name = "Doggy", imgUrl }) => {
          return (
            <Card key={crypto.randomUUID()} imgUrl={imgUrl}>
              {name}
            </Card>
          );
        })}
      </main>
    </>
  );
}
